version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      NODE_ENV: production
      PORT: 80
      DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/?retryWrites=true&w=majority
    env_file:
      - .env
    ports:
      - ${PORT:-80}:80
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD?Variable not set}
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
